apiVersion: apps/v1
kind: Deployment
metadata:
  name: realworld
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      app: realworld
  template:
    metadata:
      labels:
        app: realworld
    spec:
      containers:
        - name: realworld
          image: realworld
          ports:
            - containerPort: 5173
            