name: ci

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths-ignore:
    - "deploy/**"

jobs:
  docker:
    runs-on: macos-14
    permissions:
      id-token: write
      contents: write
      pull-requests: write
      packages: write
    steps:
      - name: Checkout PR
        uses: actions/checkout@v4
        
      - name: Setup docker (missing on MacOS)
        if: runner.os == 'macos'
        run: |
          brew install docker
          colima start

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        id: login-docker
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Docker Metadata for Api
        id: realworld-meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ steps.login-docker.outputs.registry }}/realworld
          # See: https://github.com/docker/metadata-action#tags-input
          tags: |
            type=sha

      - name: RealWorld - Build and push
        uses: docker/build-push-action@v6
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ghcr.io/ju-believer/realworld:latest
            ghcr.io/ju-believer/realworld:0.1.0  
            ghcr.io/ju-believer${{ steps.realworld-meta.outputs.tags }}

      - name: update kustomize with image 
        run: |
          git config user.name "RealworldApp GitHub Bot"
          git config user.email "<>"
          cd deploy
          kustomize edit set image "realworld=ghcr.io/ju-believer${{ steps.realworld-meta.outputs.tags }}"
          git add kustomization.yaml
          git commit -m "automated: update docker images" 
          git checkout -b bot/update-docker
          git push origin bot/update-docker

      - name: Open PR
        run: |
          gh pr create -H "bot/update-docker" -B "master" --title "automated: update docker" -b "automated: update realworld to ${{ steps.realworld-meta.outputs.tags }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} 